# fly.toml app configuration file generated for hermes-render on 2026-09-20T10:56:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hermes-render"
primary_region = 'ams'
swap_size_mb = 510

[build]
  dockerfile = "Dockerfile"

[env]
  HERMES_HOME = "/app/.hermes"
  HERMES_GATEWAY_MODE = "polling"
  GATEWAY_ALLOW_ALL_USERS = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[[vm]]
  memory_mb = 256
  cpu_kind = 'shared'
  cpus = 1
